<h1><center>Python NumPy Exercises and Techniques</h1></center>
<b>Purpose:</b> This living document is meant to service as a learning tool.

## Python and NumPy Operators

Python divides the operators in the following groups:

<li>Arithmetic operators</li>
<li>Assignment operators</li>
<li>Comparison operators</li>
<li>Logical operators</li>
<li>Identity operators</li>
<li>Membership operators</li>
<li>Bitwise operators</li>

In [1]:
# Importing numpy module
import numpy as np

# Define numpy arrays
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])

bmi = np_weight / np_height ** 2

bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In the folollowing two lines of code,, the first line is a boolean expression that returns a boolean array of the same shape as the bmi array.  The second line of code bmi[bmi > 23] is using boolean indexing to return a new array containing only those elements of bmi that satisfy the condition bmi > 23.

In [2]:
bmi > 21.76

array([ True, False, False,  True, False])

In [3]:
bmi[bmi > 21.76]

array([21.85171573, 24.7473475 ])

### Boolean Operations

In [4]:
# Importing numpy module
import numpy as np

# Creating NumPy array for BMI
bmi = np.array([21.852, 20.975, 21.75, 24.747, 21.441])

bmi > 21

array([ True, False,  True,  True,  True])

#### "logical_and", "logical_or", or "logical_not"

In this next example we see that the operators doesn't like the array to work on.  

"bmi > 21 and bmi < 22"

"ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"

The answer is to use NumPy operatores "logical_and", "logical_or", or "logical_not".

In [5]:
np.logical_and(bmi > 21, bmi < 22)

array([ True, False,  True, False,  True])

To actually select that numbers from the array just use square brackets.

In [6]:
bmi[np.logical_and(bmi > 21, bmi < 22)]

array([21.852, 21.75 , 21.441])

### Logical Operations
Using "logical_and" to compare lists.

In [7]:
# Importing numpy module
import numpy as np
  
# list 1 represents an array with boolean values
list1 = [True, False, True, False]
  
# list 2 represents an array with boolean values
list2 = [True, True, False, True]
  
# logical operations between boolean values
print('Operation between two lists =  ',
      np.logical_and(list1, list2))

Operation between two lists =   [ True False False False]


## Conditional is, else, elif
if condition :
    expression

A basic modulous (%) example.

In [8]:
z = 4
if z % 2 == 0 : 
    print("z is even")

z is even


Let's add another condition

In [9]:
Z = 4
if z % 2 == 0 :  #False
    print("z is even")
else :    
    print("z is odd")

z is even


When more customized behaviour is nessisary.

In [10]:
z = 3
if z % 2 == 0:
    print("z is divisible by 2") # False
elif z % 3 == 0:
    print("z is divisible by 3") # True
else :
    print("z is neither divisible by 2 nor by 3")

z is divisible by 3
